name: build-client

on:
  push:
    paths:
      - 'client/**'
  workflow_dispatch:

permissions: {}

jobs:
  build:
    name: 'Client: Build'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6.4.0
        with:
          node-version: 'latest'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json
      - name: Install npm deps
        run: |
          cd client/
          npm install
      - name: Build
        run: |
          cd client/
          npm run build
          mv dist/index.user.js dist/yno-ap-client.user.js
      - uses: actions/upload-artifact@v7.0.1
        with:
          path: client/dist/yno-ap-client.user.js
          archive: false