name: package-apworld

on: [workflow_dispatch]

permissions: {}

jobs:
  gen:
    name: 'APWorld: Package'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Archipelago
      uses: actions/checkout@v6
      with:
        repository: 'ArchipelagoMW/Archipelago'
        ref: '0.6.7'
    - name: Checkout yno-ap
      uses: actions/checkout@v6
      with:
        path: yno-ap
    - name: Move APWorld into Archipelago install
      run: |
        cp -r yno-ap/apworld worlds/yume2kki
        rm -rf yno-ap
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'
    - name: Install Archipelago dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ci-requirements.txt
        python ModuleUpdate.py --yes --force
        #python ModuleUpdate.py --yes --force --append "WebHostLib/requirements.txt"
        #python Launcher.py --update_settings  # make sure host.yaml exists for tests
    - name: Create .apworld file
      run: |
        python Launcher.py 'Build APWorlds' -- 'Yume 2kki'
    - uses: actions/upload-artifact@v7.0.1
      with:
        path: build/apworlds/yume2kki.apworld
        archive: false